# See https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy-web:
    name: Deploy web app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config fly.toml --remote-only --depot=false --primary-region bom -y
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  deploy-worker:
    name: Deploy worker
    runs-on: ubuntu-latest
    concurrency: deploy-group
    needs: deploy-web
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config fly.worker.toml --remote-only --depot=false --primary-region bom -y
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
